#
# Additions which are only relevant on the Raspberry Pi. Use with `-f` option,
# e.g.: `docker compose -f compose.yml -f compose.raspi.yml up`
#

services:
  proxy:
    environment:
      PROXY_PUBLIC_PORT: 80
    ports:
      - "80:80"
      - "443:443"
  devdash:
    environment:
      VITE_AUTHORITY: http://teamagochi/kc/realms/teamagochi
      VITE_CLIENT_ID: teamagochi-webapp
  teashan:
    ports:
      - "[fd00:dead:beef::1]:5683:5683/udp" # [coap://]
      - "[fd00:dead:beef::1]:5683:5683/tcp" # [coap+tcp://]
      - "[fd00:dead:beef::1]:5684:5684/udp" # [coaps://]
      - "[fd00:dead:beef::1]:5684:5684/tcp" # [coaps+tcp://]
      - "[fd00:dead:beef::1]:5685:5685/udp" # [coap://]
  keycloak:
    environment:
      KC_HOSTNAME_URL: http://teamagochi/kc
      KC_HOSTNAME_ADMIN_URL: http://teamagochi/kc
  backend:
    pull_policy: never
